experiment:
  name: null  # If null/empty, auto-generates: {env}_{exploration}_seed{seed}
  seed: 0
  n_seeds: 32

training:
  env: "custom/pointmaze-large-v0"
  bonus_type: "rnk"
  normalize_observations: true
  normalize_intrinsic_rewards: true
  total_timesteps: 1_000_000
  anneal_lr: true
  eval_freq: 8192
  num_envs: 32
  num_steps: 128
  num_epochs: 4
  num_minibatches: 32
  learning_rate: 0.0003
  max_grad_norm: 0.5
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  ext_coef: 2.0
#  bonus_params:
#    length_scale: null
#    n_samples: 128
#    n_iterations: 20
##    reg: 1e-3
