#!/bin/bash

# Common environment definitions for all exploration experiments
ENVS=(
  "MountainCar-v0"
  "Acrobot-v1"
  "Asterix-MinAtar"
  "Breakout-MinAtar"
  "Freeway-MinAtar"
  "SpaceInvaders-MinAtar"
#  "Seaquest-MinAtar"
#  "navix/Navix-Empty-8x8-v0"
#  "navix/Navix-Empty-16x16-v0"
#  "navix/Navix-DoorKey-5x5-v0"
#  "navix/Navix-DoorKey-6x6-v0"
#  "navix/Navix-DoorKey-8x8-v0"
#  "navix/Navix-DoorKey-16x16-v0"
#  "navix/Navix-FourRooms-v0"
#  "navix/Navix-SimpleCrossingS9N1-v0"
#  "navix/Navix-SimpleCrossingS9N2-v0"
#  "navix/Navix-SimpleCrossingS9N3-v0"
#  "navix/Navix-SimpleCrossingS11N5-v0"
#  "navix/Navix-DistShift1-v0"
#  "navix/Navix-DistShift2-v0"
#  "navix/Navix-LavaGapS5-v0"
#  "navix/Navix-LavaGapS6-v0"
#  "navix/Navix-LavaGapS7-v0"
#  "navix/Navix-GoToDoor-5x5-v0"
#  "navix/Navix-GoToDoor-6x6-v0"
#  "navix/Navix-GoToDoor-8x8-v0"
  "custom/pointmaze-umaze-v0"
  "custom/pointmaze-medium-v0"
  "custom/pointmaze-large-v0"
  "custom/pointmaze-giant-v0"
  "brax/sparse-ant"
  "brax/sparse-halfcheetah"
  "brax/sparse-walker2d"
  "brax/sparse-hopper"
  "brax/pusher"
  "brax/reacher"
#  "brax/ant"
#  "brax/halfcheetah"
#  "brax/walker2d"
#  "brax/hopper"
#  "brax/humanoid"
#  "brax/humanoidstandup"
)